# Generated by Django 3.1.1 on 2020-09-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_pubs',
            new_name='date_pubs',
        ),
    ]
