# Generated by Django 3.1.1 on 2020-10-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_auto_20200926_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(blank=True, db_index=True, verbose_name='Тело поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog_site.Tag', verbose_name='Теги'),
        ),
    ]
